version: '2'
services:
  mongo:
    container_name: mongo
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - spring
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    restart: always
  spring:
    container_name: spring
    image: spring
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - spring
    depends_on:
      - mongo
    environment:
      google_client_id: "google_client_id"
      smtp_username: "username"
      smtp_password: "password"
    restart: always
networks:
  spring:
volumes:
  mongo-data:
