version: '2'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    expose:
      - 3000
    ports:
    - 3000:3000
    networks:
      - spring-network
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    expose:
      - 9090
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - spring-network
    depends_on:
      - spring
  mongo:
    container_name: mongo
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - spring-network
    volumes:
      - db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "password"
  spring:
    container_name: spring
    image: spring
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - spring-network
    depends_on:
      - mongo
    environment:
      LOG_LEVEL: "DEBUG"
      MANAGEMENT_ENDPOINTS: "*"
      PROFILE: "dev"
      CLIENT_ID: "placeholder"
      MAIL_USERNAME: "placeholder"
      MAIL_PASSWORD: "placeholder"
      MONGO_HOST: "mongo"
      MONGO_USER: "mongo"
      MONGO_PASSWORD: "password"
networks:
  spring-network:
    driver: bridge
volumes:
  db-data:
    external: true
