version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

workflows:
  general:
    jobs:
      - build:
          context: SonarCloud
